source 'https://rubygems.org'
ruby "2.4.4"
gem 'sinatra'
gem "useragent"
gem 'activesupport'
gem "sitemap_generator"
gem "shotgun"
gem "pony"
gem 'handlebars'
gem 'tumblr_client'
gem 'omniauth'
gem 'json'
gem 'i18n'
gem 'strftime'
gem 'httparty'